from django.urls import path
from .views import *

urlpatterns = [
    path('faculty/', FacultyViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='faculty_list'),
    path('faculty/<int:pk>/', FacultyViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='faculty_detail'),
    path('professor/', ProfessorViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='professor_list'),
    path('professor/<int:pk>/', ProfessorViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='professor_detail'),
    path('student/', StudentViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='student_list'),
    path('student/<int:pk>/', StudentViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='student_detail'),
    path('course/', CourseViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='course_list'),
    path('course/<int:pk>/', CourseViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='course_detail'),
    path('cabinet/', CabinetViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='cabinet_list'),
    path('cabinet/<int:pk>/', CabinetViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='cabinet_detail'),
    path('timetable/', TimetableViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='timetable_list'),
    path('timetable/<int:pk>/', TimetableViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='timetable_detail'),
    path('post_course/', Post_courseViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='post_course_list'),
    path('post_course/<int:pk>/',
         Post_courseViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='post_course_detail'),
    path('homework/', HomeworkViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='homework_list'),
    path('homework/<int:pk>/', HomeworkViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='homework_detail'),
    path('post_homework/', Post_homeworkViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='post_homework_list'),
    path('post_homework/<int:pk>/',
         Post_homeworkViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='post_homework_detail'),
]
