version: '3'

services:

  web:
    build: .
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 LastProject.wsgi:application"
    volumes:
      - .:/LastProject
      - static_volume:/LastProject/static
      - media_volume:/LastProject/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/LastProject/static
      - media_volume:/LastProject/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: